### PR TITLE
Use per sub-solver dirty cache dictionary

### PR DESCRIPTION
**Pull request by sjperkins**
7c1d9f7 introduced a regression by using a single dirty dictionary for multiple solvers. This meant that
a section of data required by two solvers would be transferred to only the first, but not the second.

This change uses a dirty cache for each sub-solver, fixing the above issue. It also changes the pool reference object, holding the PyCUDA memory pool allocations, from a list to a dictionary.

### CODE REVIEW

**Comment by sjperkins** [comment]
@SpheMakh @marziarivi This fixes a serious bug. Please update your version to include master after this pull request has been merged.

**Comment by marziarivi** [comment]
Hi Simon,

1. I have just downloaded and installed the latest version of the master but when I run the tests I get:

PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.


2. If I use v5 version I get:

    pm.posangle(field_centre, zenith).get_value("rad") for t in times])
  File "/share/apps/anaconda2/lib/python2.7/site-packages/python_casacore-2.1.2-py2.7-linux-x86_64.egg/casacore/measures/__init__.py", line 933, in posangle
    return _measures.posangle(self, m0, m1)
RuntimeError: 2016-08-15 12:31:56	SEVERE	MeasTable::dUTC(Double) (file /share/apps/casacore-2.0.3/measures/Measures/MeasTable.cc, line 4328)	Cannot read leap second table TAI_UTC

Should I install casacore 2.1.0?

**Comment by sjperkins** [comment]
> 1. I have just downloaded and installed the latest version of the master but when I run the tests I get: PyCUDA ERROR: The context stack was not empty upon module cleanup. ------------------------------------------------------------------- A context was still active when the context stack was being cleaned up. At this point in our execution, CUDA may already have been deinitialized, so there is no way we can finish cleanly. The program will be aborted now. Use Context.pop() to avoid this problem.

I don't see this when running the test-suite on master on my side. Does your test.log file show any more information on the errors?

> 2. If I use v5 version I get: pm.posangle(field_centre, zenith).get_value("rad") for t in times]) File "/share/apps/anaconda2/lib/python2.7/site-packages/python_casacore-2.1.2-py2.7-linux-x86_64.egg/casacore/measures/__init__.py", line 933, in posangle return _measures.posangle(self, m0, m1) RuntimeError: 2016-08-15 12:31:56 SEVERE MeasTable::dUTC(Double) (file /share/apps/casacore-2.0.3/measures/Measures/MeasTable.cc, line 4328) Cannot read leap second table TAI_UTC Should I install casacore 2.1.0?

On Ubuntu, the `casacore-data` package provides the tables required by pyrap.

**Comment by marziarivi** [comment]
On 15 Aug 2016, at 13:57, Simon Perkins <notifications@github.com> wrote:

> I have just downloaded and installed the latest version of the master but when I run the tests I get: PyCUDA ERROR: The context stack was not empty upon module cleanup. ------------------------------------------------------------------- A context was still active when the context stack was being cleaned up. At this point in our execution, CUDA may already have been deinitialized, so there is no way we can finish cleanly. The program will be aborted now. Use Context.pop() to avoid this problem.
> I don't see this when running the test-suite on master on my side. Does your test.log file show any more information on the errors?
> 
See test.log in attachment
> If I use v5 version I get: pm.posangle(field_centre, zenith).get_value("rad") for t in times]) File "/share/apps/anaconda2/lib/python2.7/site-packages/python_casacore-2.1.2-py2.7-linux-x86_64.egg/casacore/measures/init.py", line 933, in posangle return _measures.posangle(self, m0, m1) RuntimeError: 2016-08-15 12:31:56 SEVERE MeasTable::dUTC(Double) (file /share/apps/casacore-2.0.3/measures/Measures/MeasTable.cc, line 4328) Cannot read leap second table TAI_UTC Should I install casacore 2.1.0?
> On Ubuntu, the casacore-data package provides the tables required by pyrap.
> 
> 

Is it a separate package? Could you provide me with the link?

**Comment by sjperkins** [comment]
> See test.log in attachment

I don't see it?

> Is it a separate package? Could you provide me with the link?

- On Ubuntu 14.04 you can find it on [this](https://launchpad.net/~radio-astro/+archive/ubuntu/main) PPA.
- On Ubuntu 16.04 you can find it on [this](https://launchpad.net/~kernsuite/+archive/ubuntu/kern-dev)
PPA.

**Comment by sjperkins** [comment]
@gijzelaerr Can you help @marziarivi with the source location of casacore-data? Specifically, we're looking for the measures tables.

**Comment by gijzelaerr** [comment]
the package are build weekly from the binary data from the svn server of astron:

ftp://ftp.astron.nl/outgoing/Measures/

**Comment by marziarivi** [comment]
I have downloaded ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures_20160815-000001.ztar and but everything in DATA_DIR (specified when casacore was installed).

Now I get:

File "/share/apps/anaconda2/lib/python2.7/site-packages/montblanc-0.4.0_alpha3_285_g487a077-py2.7.egg/montblanc/impl/rime/v5/loaders/loaders.py", line 299, in load
    solver.parallactic_angles[:] = mbu.parallactic_angles(phase_dir, ref_ant_position, times)
  File "/share/apps/anaconda2/lib/python2.7/site-packages/montblanc-0.4.0_alpha3_285_g487a077-py2.7.egg/montblanc/util/__init__.py", line 433, in parallactic_angles
    import pyrap.measures
  File "/share/apps/anaconda2/lib/python2.7/site-packages/python_casacore-2.1.2-py2.7-linux-x86_64.egg/pyrap/measures.py", line 1, in <module>
    from casacore.measures import *
  File "/share/apps/anaconda2/lib/python2.7/site-packages/python_casacore-2.1.2-py2.7-linux-x86_64.egg/casacore/measures/__init__.py", line 30, in <module>
    import casacore.quanta as dq
  File "/share/apps/anaconda2/lib/python2.7/site-packages/python_casacore-2.1.2-py2.7-linux-x86_64.egg/casacore/quanta/__init__.py", line 1, in <module>
    from .quantity import quantity, is_quantity
  File "/share/apps/anaconda2/lib/python2.7/site-packages/python_casacore-2.1.2-py2.7-linux-x86_64.egg/casacore/quanta/quantity.py", line 2, in <module>
    from ._quanta import Quantity
ImportError: /share/apps/anaconda2/lib/python2.7/site-packages/python_casacore-2.1.2-py2.7-linux-x86_64.egg/casacore/quanta/_quanta.so: undefined symbol: _ZNK4casa8UnitName11getFullNameEv

**Comment by sjperkins** [comment]
@marziarivi Perhaps a rebuild of python-casacore is required?

**Comment by marziarivi** [comment]
Ok. Now it works but I get bad values for the numerical gradient (X2 differences). With the previous version of the master it worked...

**Comment by sjperkins** [comment]
@marziarivi I've found something. This [line](https://github.com/ska-sa/montblanc/blob/487a077fee273a08a0e5a5a2a80cffa2fcd1a81a/montblanc/impl/rime/v5/CompositeRimeSolver.py#L868) needs `d.clear` to change to `d.clear()`.

I'm trying to do more checks on my side, but I've shifted onto a new Ubuntu 16.04 laptop and I'm fighting with broken packages. But see if the above helps?

**Comment by marziarivi** [comment]
Ok. Now it works.

**Pull request merged**
