### PR TITLE
[WIP] Fixes deadlocking queue inside montblanc

### PR DESCRIPTION
**Pull request by bennahugo**
This is a decrement before lock scenario. The feeder queue has its own lock - however before increment can take place on inputs waiting consume must have already tried decrementing the counter and one of the while loops hangs forever at that point. This is non-deterministic.

Specifically this entire block:
```
                try:
                    # Get the descriptor describing a portion of the RIME
                    result = session.run(LSA.descriptor.get_op)
                    descriptor = result['descriptor']
                except tf.errors.OutOfRangeError as e:
                    montblanc.log.exception("Descriptor reading exception")

                # Quit if EOF
                if descriptor[0] == -1:
                    break

                # Make it read-only so we can hash the contents
                descriptor.flags.writeable = False

                # Find indices of the emptiest staging_areas and, by implication
                # the shard with the least work assigned to it
                emptiest_staging_areas = np.argsort(self._inputs_waiting.get())
                shard = emptiest_staging_areas[0]
                shard = next(which_shard)
                feed_f = self._feed_executors[shard].submit(self._feed_actual,
                    data_sources.copy(), cube.copy(),
                    descriptor, shard,
                    src_types, src_strides, src_staging_areas[shard],
                    global_iter_args)

                compute_f = self._compute_executors[shard].submit(self._compute,
                    compute_feed_dict, shard)

                consume_f = self._consumer_executor.submit(self._consume,
                    data_sinks.copy(), cube.copy(), global_iter_args)

                self._inputs_waiting.increment(shard)

                yield (feed_f, compute_f, consume_f)

                chunks_fed += 1
```
ought to be inside a lock because there are variables outside the _inputs_waiting queue that must only be updated while the lock is held by the queue

### CODE REVIEW

**Review by sjperkins — CHANGES_REQUESTED** [review]
I'm not convinced that this addresses the deadlock (which are notoriously difficult to identify). `_inputs_waiting` exists to identify which shard is least subscribed in terms of input data. Thus, the `_inputs.waiting.increment` and `_inputs_waiting.decrement` methods keep track of how many input chunks are in flight, and this is protected by a lock.

However, this is not actually currently used to determine the shard to which a chunk is assigned. Looking more closely at the following 3 lines:

```python
emptiest_staging_areas = np.argsort(self._inputs_waiting.get())
shard = emptiest_staging_areas[0]
shard = next(which_shard)
```

we can see that the choice of the emptiest staging area is ignored. In fact, the choice is given to the cyclic iterator `which_shard` which merely round-robins input chunks over the shards.

In fact, I think the `_inputs_waiting` mechanism could be removed as it doesn't actually impact existing functionality.

However, I'm not convinced that this will deal with the deadlock that you are observing

**Comment by bennahugo** [comment]
Alright that certainly looks like it has fixed it. I've set the WIP porting branch of DDFacet to test with this branch and it has run through

**Comment by sjperkins** [comment]
Putting a single lock around the `get` and `put` of a queue will `fix` it but its not a correct solution because it'll decrease throughput -- Multiple producers and consumers will have to wait to obtain that lock before putting data onto, or removing data from, the queue.

**Comment by bennahugo** [comment]
Alright as discussed offline I've added a fine-grained locking mechanism on the shard feeder to ensure compute only starts when the shard has been loaded with data. As per our inspection the collector uses a tensorflow staging area which will block according to documentation upon get when data is not available. I've tested this upstream in DDFacet on larger data where it always locked up and it is running now.

**Comment by bennahugo** [comment]
Before merging I just want to check for severe performance regression -- I'm running a larger imaging job where Montblanc is used in ddfacet to do this

**Comment by bennahugo** [comment]
On 2000 components this shows no regression in compute time so I'm gong to merge this

**Pull request merged**
