### PR TITLE
Compare Meqtree and Montblanc beam implementations

### PR DESCRIPTION
**Pull request by sjperkins**
Add functionality to `test_cmp_vis` to compare MeqTree and Montblanc beam implementations.

### CODE REVIEW

**Comment by sjperkins** [comment]
# Off-centre 1Jy source with some U, Q, V parameters

``` bash
#format: ra_d dec_d i q u v spi freq0
0.0922490031602 60.2062332956 1.0 0.2 0.25 0.3 0.8 1500000000.0
```

I get the following (normalised) root mean square deviations between visibilities.

- RMSD Amplitude 0.101240947312 Phase 0.384493768303
- NRMSD Amplitude 0.0363659721145 Phase 0.0611940960427
- Montblanc Amplitude min 0.140220984817 max 1.02211117744 Phase min -3.14158630371 max 3.1415913105
- Meqtrees Amplitude min 0.131913289428 max 2.91586041451 Phase min -3.14159202576 max 3.14159226418

The plots in casa are very similar, although MeqTrees has some stray visibilities with amplitude > 1 and hence the high max amp. A


Sample visibilities:

- Meqtrees abs [ 0.90971124  0.29287067  0.29287079  0.58212346]
- Montblanc abs [ 0.92279851  0.29784489  0.29784486  0.59127712]
- Meqtrees phase [-3.00655937 -1.07344651  1.34351254 -3.00656009]
- Montblanc phase [-3.00655603 -1.03139508  1.30146825 -3.00655603]


# On-centre 1Jy source with zeroed Q, U and V

```bash
#format: ra_d dec_d i q u v spi freq0
0.0 60.0 1.0 0 0 0 0.8 1500000000.0
```

I get the following (normalised) root mean square deviations between visibilities.

- RMSD Amplitude 0.259349373612 **Phase 2.28634366603**
- NRMSD Amplitude 0.0931588684132 Phase **0.363882968776**
- Montblanc Amplitude min 0.000574026780669 max 0.92484152317 Phase min -3.10075092316 max 3.10075092316
- Meqtrees Amplitude min 0.131913289428 max 2.91586041451 Phase min -3.14159202576 max 3.14159226418

Interesting thing about this case is that the phase should be close to zero -- Montblanc seems to get this right on XX and YY, but not XY and YX. 

Sample visibilities
- Meqtrees abs [ 0.90971124  0.29287067  0.29287079  0.58212346]
- Montblanc abs [ 0.89056981  0.00986505  0.00986505  0.85491461]
- Meqtrees phase [-3.00655937 -1.07344651  1.34351254 -3.00656009]
- Montblanc phase [  3.96951716e-09   3.06029034e+00  -3.06029034e+00  -2.23885532e-09]

# Amplitude Plots

MeqTrees

meqtrees

Montblanc

montblanc

# Questions

- Is the above close enough?
- `pybeams_fits.ampl_interpolation = 1`, this falls over for On-centre test case with lots of
**785: node 'sink:3:12': shape of child result does not match output column (while getting result for request ev.0.0.0.8.1)**
- Are our complex interpolation methods the same?
  - [MeqTrees](https://github.com/ska-sa/meqtrees-cattery/blob/master/Cattery/Siamese/OMS/InterpolatedBeams.py#L330-L334)
  - [Montblanc](https://github.com/ska-sa/montblanc/blob/f7df35359d36de8ccdec4f0aa27494d13307bed4/montblanc/impl/rime/v4/cpu/CPUSolver.py#L431-L491)

**Comment by sjperkins** [comment]
@o-smirnov Can you comment on the above? Posted it in case you can spot something quickly. Looks like our amplitudes/phase are out by 3.6%/6.1% for the off-centre case and 9.3%/36.3% for on-centre but I think MeqTrees might not be handling things correctly on the phase.

**Comment by o-smirnov** [comment]
Which beam patterns are these? I'm a bit worried about the MeqTrees visibilities being so high (2.91 max ampl?), something seems awry. Can you point me where you have the simulations set up? I'd like to see your .tdl.conf etc. and maybe run it myself.

The error you're seeing is due to an edge case when the output visibilities have no dependence on time. In this case MeqTrees "collapses" the time axis to save computation, but there's a bug in the output layer that doesn't like to deal with such visibilities (and given the impossibility of them arising in real life, the bug never got fixed...)

**Comment by sjperkins** [comment]
They're JVLA circular beams, renamed so that meqtrees thinks they're linear and with their frequency dimensions reconfigured so that they match that of the associated MS.

Here is the [https://github.com/ska-sa/montblanc/blob/c65d346db3763b00f53477999def00ed07e1575f/montblanc/tests/meqtrees/tdlconf.profiles](https://github.com/ska-sa/montblanc/blob/c65d346db3763b00f53477999def00ed07e1575f/montblanc/tests/meqtrees/tdlconf.profiles) (ampl_interpolation turned off though).

Its all setup on my laptop, I can setup the problem on ray if you want to investigate further.

**Comment by o-smirnov** [comment]
Yes please do, if you can just point me to a directory on ray that'd be optimal.

**Comment by sjperkins** [comment]
Performed an implementation of meqtrees beam interpolation [here](https://github.com/ska-sa/montblanc/blob/0efca46220b99445662e0af9078043cda43bf0f6/montblanc/impl/rime/v4/cpu/CPUSolver.py#L489-L519) (via scipy.ndimage.interpolation).in Montblanc's CPU solver. Results agree. Implies that either sampling coordinates are off or beam coordinate system is out.

**Comment by o-smirnov** [comment]
OK sorry, haven't been able to get to it while travelling, but offhand:

* "nearest" probably better as a fallback outside the beam, but this is a very minor wrinkle anyway

* beam coordinate systems being off is **extremely** likely. You need to be very lucky to get this stuff right on the first go, there's almost always a sign flip or something... this is why such comparisons are very useful.

**Comment by sjperkins** [comment]
Parallactic Angles are very similar (delta of 2.7e-5 degrees on l) -- compare the first/last 8 elements from montblanc with the first and last interpolation chunks (eight sources right?) from meqtrees. 

```python
# Montblanc
l [[ -3.82431259e-04  -2.78646126e-04  -1.74349581e-04  -6.96459902e-05
    3.53573123e-05   1.40549731e-04   2.45818344e-04   3.51048162e-04
    4.56122769e-04   5.60924760e-04   6.65336265e-04   7.69239559e-04
    8.72517412e-04   9.75053990e-04   1.07673486e-03   1.17744820e-03
    1.27708446e-03   1.37553783e-03   1.47270516e-03   1.56848819e-03
    1.66279275e-03   1.75552908e-03   1.84661243e-03   1.93596305e-03
    2.02350668e-03   2.10917438e-03   2.19290238e-03   2.27463222e-03
    2.35431152e-03   2.43189279e-03   2.50733318e-03   2.58059544e-03
    2.65164743e-03   2.72046030e-03   2.78701121e-03   2.85127992e-03
    2.91325012e-03   2.97290925e-03   3.03024729e-03   3.08525679e-03
    3.13793262e-03   3.18827108e-03   3.23627004e-03   3.28192674e-03
    3.32524115e-03   3.36621027e-03   3.40483151e-03   3.44110047e-03
    3.47501063e-03   3.50655150e-03   3.53570934e-03   3.56246531e-03
    3.58679472e-03   3.60866450e-03   3.62803298e-03   3.64484731e-03
    3.65904090e-03   3.67053226e-03   3.67921917e-03   3.68497521e-03
    3.68764531e-03   3.68703762e-03   3.68291512e-03   3.67498491e-03
    3.66288098e-03   3.64614790e-03   3.62421083e-03   3.59634287e-03
    3.56161664e-03   3.51883494e-03   3.46644316e-03   3.40239727e-03]]
m [[  3.66793480e-03   3.67727573e-03   3.68369417e-03   3.68716009e-03
    3.68764810e-03   3.68513842e-03   3.67961568e-03   3.67107126e-03
    3.65950167e-03   3.64490924e-03   3.62730306e-03   3.60669801e-03
    3.58311483e-03   3.55658121e-03   3.52712930e-03   3.49479821e-03
    3.45963216e-03   3.42168030e-03   3.38099664e-03   3.33764055e-03
    3.29167419e-03   3.24316486e-03   3.19218147e-03   3.13879689e-03
    3.08308611e-03   3.02512548e-03   2.96499231e-03   2.90276553e-03
    2.83852359e-03   2.77234521e-03   2.70430767e-03   2.63448781e-03
    2.56296038e-03   2.48979777e-03   2.41507078e-03   2.33884668e-03
    2.26118835e-03   2.18215724e-03   2.10180879e-03   2.02019559e-03
    1.93736353e-03   1.85335567e-03   1.76820718e-03   1.68194971e-03
    1.59460702e-03   1.50619680e-03   1.41672930e-03   1.32620777e-03
    1.23462616e-03   1.14197074e-03   1.04821706e-03   9.53330542e-04
    8.57264618e-04   7.59960560e-04   6.61344850e-04   5.61328023e-04
    4.59801930e-04   3.56639328e-04   2.51687306e-04   1.44767982e-04
    3.56697710e-05  -7.58533715e-05  -1.90092018e-04  -3.07386508e-04
   -4.28137631e-04  -5.52816782e-04  -6.81979524e-04  -8.16281652e-04
   -9.56497795e-04  -1.10353983e-03  -1.25847966e-03  -1.42256496e-03]]

# MeqTrees First Chunk
Interpolating (
l [ -3.81962134e-04  -2.78175532e-04  -1.73878090e-04  -6.91741092e-05
   3.58288134e-05   1.41020184e-04   2.46287043e-04   3.51514475e-04],
m [ 0.00366798  0.00367731  0.00368372  0.00368717  0.00368764  0.00368512
  0.00367958  0.00367103])

# Meqtrees Last Chunk
 l  [ 0.00366262  0.0036458   0.00362376  0.00359579  0.00356093  0.003518
  0.00346543  0.00340116],
m [-0.00043037 -0.00055511 -0.00068435 -0.00081874 -0.00095905 -0.00110621
 -0.00126128 -0.00142552]
```

**Comment by sjperkins** [comment]
1. Is there any other angle meqtrees is including in the rotation (feed angle for instance, although this is a generated MS I'm working with)?

2. I've configured my beam coordinates system [here](https://github.com/ska-sa/montblanc/blob/0efca46220b99445662e0af9078043cda43bf0f6/montblanc/tests/test_cmp_vis.py#L250-L254). I'm assuming that thats the right way to get the bottom lm and top lm coordinates of the cube in radians (axis was converted on line 236)

**Comment by sjperkins** [comment]
Changed second to last comment to refer to lm coordinate rotated by parallactic angle.

**Comment by o-smirnov** [comment]
OK maybe need to pump up the verbosity of ``pybeams_fits`` in MeqTrees and look at the actual pixel coordinates being interpolated to, compare that to Montblanc's.

**Comment by sjperkins** [comment]
OK, I was trying to figure out the verbosity context for it yesterday, thought it was vb.

Currently trying imaging the meqtrees/Montblanc visibilities

**Comment by sjperkins** [comment]
Did a more in-depth comparison. Here is a sample lm and grid coordinate with interpolated value. This point and interpolated values are similar enough that I'm loathe to invest more time on this. However, the resultant error in visibilities is still pretty large (they agree with a relative tolerance of 10!). I might dig into this a little more on Monday.

```python
# lm coordinates
Montblanc (0.00120485597290098667,   0.00348544423468410969) 
MeqTrees  (0.00120456290074      ,   0.00348554561313      )

Percent Difference                 (0.02432425, -0.00290862)

# grid coordinates
Montblanc (65.02236175537109375000, 70.74318695068359375000)
MeqTrees  (65.0216288557          , 70.7434414559          )

Percent Difference                 (0.00112715, -0.00035976)

# interpolated value
Montblanc (0.18798351287841796875 + 0.87773466110229492188j)
MeqTrees  (0.187992771299         + 0.877730219022j        )

Percent Difference Amplitude 2.6788354710668912e-06
Percent Difference Phase     8.1789473662078448e-06
```

Here's a diff image of the the imaged visibilities in tigger (the images themselves are highly similar to the eye)

mb_meq_diff

**Comment by o-smirnov** [comment]
I agree that the interpolated values are close enough to not worry about it. Very curious that the lm coordinates differ so much though -- presumably we should be using the same formulae, so what gives? This is worth checking out.

Even more importantly, the visibilities have to agree. Something is going very wrong somewhere!

**Comment by o-smirnov** [comment]
P.S. Where are the simulated sources w.r.t. the difference map?

**Comment by sjperkins** [comment]
- I disagree on the coordinates, both the lm and grid coordinates are highly similar!
- But I do agree that it would be good to have visibilities agreeing (more on this to come)
- The source is at (0.0008, 0.0036) radians.

I did some more digging on this and I think this a problem similar to one I encountered when comparing montblanc's CPU test beam vs montblanc's GPU beam. It all boils down to the fact that since we're linearly interpolating there are going to be cases where an interpolation point is marginally on the edge of a grid cell. On one implementation that point will fall below the edge and other it will fall above, leading to interpolation occurring in completely different grid cells. The proper solution to this is higher order splines, but I don't have a GPU kernel for this.

This is obviously happening on the frequency axis and probably because frequencies over 64 channels map conveniently close to grid points for a cube with 1024 frequency slices. I'm going to try and get them to interpolate closer to the middle of the cube voxels tomorrow.

But at the end of the day, there are just going to be differing E jones terms due to linear interpolation.

**Pull request merged**
