### PR TITLE
E Beam Cube and G term implementation in v4

### PR DESCRIPTION
**Pull request by sjperkins**
This pull request implements the E Beam cube and G term in version four.

The underlying thread model for this change assumes a polarisation per thread, rather than a visibility per thread. Kepler shuffle instructions are employed to achieve a full Jones matrix multiply amongst groups of four threads (polarisations).

Oleg, please don't push the button yet :-D

### CODE REVIEW

**Comment by sjperkins** [comment]
@o-smirnov Please press the button!

The Button

**Comment by sjperkins** [comment]
@o-smirnov Actually hold back, there's one more change I want to make!

**Comment by o-smirnov** [comment]
ok :)

**Comment by sjperkins** [comment]
@o-smirnov Ready to go!

**Comment by o-smirnov** [comment]
Damn, I wanted to push that button myself, but I'm on 300 baud Internet
here!

**Comment by sjperkins** [comment]
@o-smirnov If you use **two** carrier pigeons, you could get 600 baud! I'm sure there'll be more opportunities to push the button up the road.

**Pull request merged**
